version: 2
updates:
- package-ecosystem: elm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: regex
    versions:
    - 1.4.3
    - 1.4.4
    - 1.4.5
  - dependency-name: reqwest
    versions:
    - 0.11.0
    - 0.11.1
    - 0.11.2
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: tracing-subscriber
    versions:
    - 0.2.16
  - dependency-name: tracing
    versions:
    - 0.1.23
    - 0.1.24
  - dependency-name: hocon
    versions:
    - 0.4.0
